# Generated by Django 5.1.2 on 2024-11-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_picture',
            field=models.CharField(default='cover_picture.png', max_length=500),
        ),
    ]
