# Generated by Django 5.1.2 on 2024-11-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_user_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_user_b',
            field=models.BooleanField(default=False),
        ),
    ]
