# Generated by Django 5.1.2 on 2024-11-13 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.TextField(blank=True, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='file'),
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='app.user')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='app.user')),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
