# Generated by Django 5.1.2 on 2024-10-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='room_name',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to='app.user'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chat_rooms', through='app.UserChatRoom', to='app.user'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='Default Room', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat_rooms/'),
        ),
    ]
